import React from 'react';

const Footer = () => {
  return (
    <div className="bg-black text-white flex flex-col gap-6 items-center py-10">
      <h2 className="text-4xl font-bold uppercase">whatsapp now</h2>
      <div className="flex flex-col sm:flex-row gap-5 px-4 max-w-4xl mx-auto">
        <img
          src="https://lotus365.blue/assets/img/gaming-1.png"
          alt="logo"
          className="sm:w-1/5 w-1/2"
        />
        <p className="text-xs">
          lotus365 is a limited liability company incorporated under the laws of
          Curacao Players are requested not to contact any untrusted sources for
          lotus365 accounts as this is an online site and they can only register
          independently without any agents. Only deposit through the account
          details generated by the system or provided by our official support
          team.
        </p>
      </div>
      <div className="flex gap-5 max-w-4xl mx-auto">
        {Array.from({ length: 4 }, (_, index) => (
          <img
            src={`/asset ${33 + index}.svg`}
            alt={index}
            key={index}
            className="w-1/5"
          />
        ))}
      </div>
      <hr className="border-b w-full border-gray-800" />
      <p className="text-gray-300 text-sm">
        RulesRegulations 2016-2030 v. 9.94
      </p>
    </div>
  );
};

export default Footer;
